//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 07:20:20 PM CEST 
//


package de.l3s.article;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}resources"/>
 *         &lt;element ref="{}comments"/>
 *         &lt;element ref="{}resources_rates"/>
 *         &lt;element ref="{}comments_rates"/>
 *         &lt;element ref="{}tags"/>
 *         &lt;element ref="{}feedback_balance"/>
 *         &lt;element ref="{}abuses"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resources",
    "comments",
    "resourcesRates",
    "commentsRates",
    "tags",
    "feedbackBalance",
    "abuses"
})
@XmlRootElement(name = "counters")
public class Counters {

    @XmlElement(required = true)
    protected BigInteger resources;
    @XmlElement(required = true)
    protected BigInteger comments;
    @XmlElement(name = "resources_rates", required = true)
    protected BigInteger resourcesRates;
    @XmlElement(name = "comments_rates", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String commentsRates;
    @XmlElement(required = true)
    protected BigInteger tags;
    @XmlElement(name = "feedback_balance", required = true)
    protected String feedbackBalance;
    @XmlElement(required = true)
    protected BigDecimal abuses;

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResources(BigInteger value) {
        this.resources = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setComments(BigInteger value) {
        this.comments = value;
    }

    /**
     * Gets the value of the resourcesRates property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResourcesRates() {
        return resourcesRates;
    }

    /**
     * Sets the value of the resourcesRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResourcesRates(BigInteger value) {
        this.resourcesRates = value;
    }

    /**
     * Gets the value of the commentsRates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentsRates() {
        return commentsRates;
    }

    /**
     * Sets the value of the commentsRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentsRates(String value) {
        this.commentsRates = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTags(BigInteger value) {
        this.tags = value;
    }

    /**
     * Gets the value of the feedbackBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeedbackBalance() {
        return feedbackBalance;
    }

    /**
     * Sets the value of the feedbackBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeedbackBalance(String value) {
        this.feedbackBalance = value;
    }

    /**
     * Gets the value of the abuses property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAbuses() {
        return abuses;
    }

    /**
     * Sets the value of the abuses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAbuses(BigDecimal value) {
        this.abuses = value;
    }

}
