//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 07:25:57 PM CEST 
//


package de.l3s.article;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}web_url"/>
 *         &lt;element ref="{}snippet"/>
 *         &lt;element ref="{}lead_paragraph"/>
 *         &lt;element ref="{}abstract"/>
 *         &lt;element ref="{}print_page"/>
 *         &lt;element ref="{}source"/>
 *         &lt;element ref="{}multimedia" maxOccurs="unbounded"/>
 *         &lt;element ref="{}headline"/>
 *         &lt;element ref="{}keywords" maxOccurs="unbounded"/>
 *         &lt;element ref="{}pub_date"/>
 *         &lt;element ref="{}document_type"/>
 *         &lt;element ref="{}news_desk"/>
 *         &lt;element ref="{}section_name"/>
 *         &lt;element ref="{}subsection_name"/>
 *         &lt;element ref="{}byline"/>
 *         &lt;element ref="{}type_of_material"/>
 *         &lt;element ref="{}_id"/>
 *         &lt;element ref="{}word_count"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "webUrl",
    "snippet",
    "leadParagraph",
    "_abstract",
    "printPage",
    "source",
    "multimedia",
    "headline",
    "keywords",
    "pubDate",
    "documentType",
    "newsDesk",
    "sectionName",
    "subsectionName",
    "byline",
    "typeOfMaterial",
    "id",
    "wordCount"
})
@XmlRootElement(name = "docs")
public class Docs {

    @XmlElement(name = "web_url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String webUrl;
    @XmlElement(required = true)
    protected String snippet;
    @XmlElement(name = "lead_paragraph", required = true)
    protected String leadParagraph;
    @XmlElement(name = "abstract", required = true)
    protected String _abstract;
    @XmlElement(name = "print_page", required = true)
    protected String printPage;
    @XmlElement(required = true)
    protected String source;
    @XmlElement(required = true)
    protected List<Multimedia> multimedia;
    @XmlElement(required = true)
    protected Headline headline;
    @XmlElement(required = true)
    protected List<Keywords> keywords;
    @XmlElement(name = "pub_date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pubDate;
    @XmlElement(name = "document_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String documentType;
    @XmlElement(name = "news_desk", required = true)
    protected String newsDesk;
    @XmlElement(name = "section_name", required = true)
    protected String sectionName;
    @XmlElement(name = "subsection_name", required = true)
    protected String subsectionName;
    @XmlElement(required = true)
    protected Byline byline;
    @XmlElement(name = "type_of_material", required = true)
    protected String typeOfMaterial;
    @XmlElement(name = "_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;
    @XmlElement(name = "word_count", required = true)
    protected String wordCount;

    /**
     * Gets the value of the webUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * Sets the value of the webUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebUrl(String value) {
        this.webUrl = value;
    }

    /**
     * Gets the value of the snippet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnippet() {
        return snippet;
    }

    /**
     * Sets the value of the snippet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnippet(String value) {
        this.snippet = value;
    }

    /**
     * Gets the value of the leadParagraph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadParagraph() {
        return leadParagraph;
    }

    /**
     * Sets the value of the leadParagraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadParagraph(String value) {
        this.leadParagraph = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the printPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintPage() {
        return printPage;
    }

    /**
     * Sets the value of the printPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintPage(String value) {
        this.printPage = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the multimedia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multimedia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultimedia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Multimedia }
     * 
     * 
     */
    public List<Multimedia> getMultimedia() {
        if (multimedia == null) {
            multimedia = new ArrayList<Multimedia>();
        }
        return this.multimedia;
    }

    /**
     * Gets the value of the headline property.
     * 
     * @return
     *     possible object is
     *     {@link Headline }
     *     
     */
    public Headline getHeadline() {
        return headline;
    }

    /**
     * Sets the value of the headline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Headline }
     *     
     */
    public void setHeadline(Headline value) {
        this.headline = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keywords }
     * 
     * 
     */
    public List<Keywords> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<Keywords>();
        }
        return this.keywords;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * Sets the value of the pubDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubDate(String value) {
        this.pubDate = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the newsDesk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsDesk() {
        return newsDesk;
    }

    /**
     * Sets the value of the newsDesk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsDesk(String value) {
        this.newsDesk = value;
    }

    /**
     * Gets the value of the sectionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * Sets the value of the sectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectionName(String value) {
        this.sectionName = value;
    }

    /**
     * Gets the value of the subsectionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsectionName() {
        return subsectionName;
    }

    /**
     * Sets the value of the subsectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsectionName(String value) {
        this.subsectionName = value;
    }

    /**
     * Gets the value of the byline property.
     * 
     * @return
     *     possible object is
     *     {@link Byline }
     *     
     */
    public Byline getByline() {
        return byline;
    }

    /**
     * Sets the value of the byline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byline }
     *     
     */
    public void setByline(Byline value) {
        this.byline = value;
    }

    /**
     * Gets the value of the typeOfMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfMaterial() {
        return typeOfMaterial;
    }

    /**
     * Sets the value of the typeOfMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfMaterial(String value) {
        this.typeOfMaterial = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the wordCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordCount() {
        return wordCount;
    }

    /**
     * Sets the value of the wordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordCount(String value) {
        this.wordCount = value;
    }

}
