//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 07:25:57 PM CEST 
//


package de.l3s.article;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}seo" minOccurs="0"/>
 *         &lt;element ref="{}main"/>
 *         &lt;element ref="{}content_kicker" minOccurs="0"/>
 *         &lt;element ref="{}kicker" minOccurs="0"/>
 *         &lt;element ref="{}print_headline" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seo",
    "main",
    "contentKicker",
    "kicker",
    "printHeadline"
})
@XmlRootElement(name = "headline")
public class Headline {

    protected String seo;
    @XmlElement(required = true)
    protected String main;
    @XmlElement(name = "content_kicker")
    protected String contentKicker;
    protected String kicker;
    @XmlElement(name = "print_headline")
    protected String printHeadline;

    /**
     * Gets the value of the seo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeo() {
        return seo;
    }

    /**
     * Sets the value of the seo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeo(String value) {
        this.seo = value;
    }

    /**
     * Gets the value of the main property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMain() {
        return main;
    }

    /**
     * Sets the value of the main property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMain(String value) {
        this.main = value;
    }

    /**
     * Gets the value of the contentKicker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentKicker() {
        return contentKicker;
    }

    /**
     * Sets the value of the contentKicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentKicker(String value) {
        this.contentKicker = value;
    }

    /**
     * Gets the value of the kicker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKicker() {
        return kicker;
    }

    /**
     * Sets the value of the kicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKicker(String value) {
        this.kicker = value;
    }

    /**
     * Gets the value of the printHeadline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintHeadline() {
        return printHeadline;
    }

    /**
     * Sets the value of the printHeadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintHeadline(String value) {
        this.printHeadline = value;
    }

}
