//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 07:25:57 PM CEST 
//


package de.l3s.article;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}wide"/>
 *           &lt;element ref="{}wideheight"/>
 *           &lt;element ref="{}widewidth"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}xlargewidth"/>
 *           &lt;element ref="{}xlarge"/>
 *           &lt;element ref="{}xlargeheight"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}thumbnailheight"/>
 *           &lt;element ref="{}thumbnail"/>
 *           &lt;element ref="{}thumbnailwidth"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wide",
    "wideheight",
    "widewidth",
    "xlargewidth",
    "xlarge",
    "xlargeheight",
    "thumbnailheight",
    "thumbnail",
    "thumbnailwidth"
})
@XmlRootElement(name = "legacy")
public class Legacy {

    protected String wide;
    protected BigInteger wideheight;
    protected BigInteger widewidth;
    protected BigInteger xlargewidth;
    protected String xlarge;
    protected BigInteger xlargeheight;
    protected BigInteger thumbnailheight;
    protected String thumbnail;
    protected BigInteger thumbnailwidth;

    /**
     * Gets the value of the wide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWide() {
        return wide;
    }

    /**
     * Sets the value of the wide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWide(String value) {
        this.wide = value;
    }

    /**
     * Gets the value of the wideheight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWideheight() {
        return wideheight;
    }

    /**
     * Sets the value of the wideheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWideheight(BigInteger value) {
        this.wideheight = value;
    }

    /**
     * Gets the value of the widewidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidewidth() {
        return widewidth;
    }

    /**
     * Sets the value of the widewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidewidth(BigInteger value) {
        this.widewidth = value;
    }

    /**
     * Gets the value of the xlargewidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXlargewidth() {
        return xlargewidth;
    }

    /**
     * Sets the value of the xlargewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXlargewidth(BigInteger value) {
        this.xlargewidth = value;
    }

    /**
     * Gets the value of the xlarge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXlarge() {
        return xlarge;
    }

    /**
     * Sets the value of the xlarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXlarge(String value) {
        this.xlarge = value;
    }

    /**
     * Gets the value of the xlargeheight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXlargeheight() {
        return xlargeheight;
    }

    /**
     * Sets the value of the xlargeheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXlargeheight(BigInteger value) {
        this.xlargeheight = value;
    }

    /**
     * Gets the value of the thumbnailheight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThumbnailheight() {
        return thumbnailheight;
    }

    /**
     * Sets the value of the thumbnailheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThumbnailheight(BigInteger value) {
        this.thumbnailheight = value;
    }

    /**
     * Gets the value of the thumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * Sets the value of the thumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbnail(String value) {
        this.thumbnail = value;
    }

    /**
     * Gets the value of the thumbnailwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThumbnailwidth() {
        return thumbnailwidth;
    }

    /**
     * Sets the value of the thumbnailwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThumbnailwidth(BigInteger value) {
        this.thumbnailwidth = value;
    }

}
