//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 07:25:57 PM CEST 
//


package de.l3s.article;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}rank"/>
 *         &lt;element ref="{}firstname"/>
 *         &lt;element ref="{}lastname"/>
 *         &lt;element ref="{}middlename"/>
 *         &lt;element ref="{}organization"/>
 *         &lt;element ref="{}role"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rankOrFirstnameOrLastname"
})
@XmlRootElement(name = "person")
public class Person {

    @XmlElementRefs({
        @XmlElementRef(name = "organization", type = Organization.class, required = false),
        @XmlElementRef(name = "lastname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "role", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "middlename", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "firstname", type = JAXBElement.class, required = false)
    })
    protected List<Object> rankOrFirstnameOrLastname;

    /**
     * Gets the value of the rankOrFirstnameOrLastname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rankOrFirstnameOrLastname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRankOrFirstnameOrLastname().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Organization }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getRankOrFirstnameOrLastname() {
        if (rankOrFirstnameOrLastname == null) {
            rankOrFirstnameOrLastname = new ArrayList<Object>();
        }
        return this.rankOrFirstnameOrLastname;
    }

}
